using System.Text;
using forge.Models;
using Spectre.Console;

namespace forge;

/// <summary>
/// Writes <c>CMakePresets.json</c>, mirroring the configure settings Forge
/// passes on the command line so IDEs (VS Code CMake Tools, CLion) and plain
/// <c>cmake --preset forge</c> see exactly the same configuration.
/// </summary>
public static class CMakePresetsManager
{
  public const string FileName = "CMakePresets.json";

  /// <summary>The preset name, also used to recognise a Forge-generated file.</summary>
  public const string PresetName = "forge";

  /// <summary>
  /// Writes the preset file, unless the project already has a hand-written one
  /// (a file without a preset named <c>forge</c> is left untouched).
  /// </summary>
  public static void Write(string generator,
                           IReadOnlyDictionary<string, string> cacheVariables)
  {
    var path = Path.Combine(Directory.GetCurrentDirectory(), FileName);
    if (File.Exists(path))
    {
      var existing = File.ReadAllText(path);
      if (!existing.Contains($"\"{PresetName}\"", StringComparison.Ordinal))
      {
        AnsiConsole.MarkupLine(
          $"[dim]Note: {FileName} exists and was not generated by Forge; leaving it alone.[/]");
        return;
      }
    }

    var sb = new StringBuilder();
    sb.AppendLine("{");
    // Schema 4 matches the project's CMake minimum (3.23); it covers
    // cacheVariables, binaryDir, generator and build presets.
    sb.AppendLine("  \"version\": 4,");
    sb.AppendLine("  \"configurePresets\": [");
    sb.AppendLine("    {");
    sb.AppendLine($"      \"name\": \"{PresetName}\",");
    sb.AppendLine("      \"displayName\": \"Forge (generated)\",");
    sb.AppendLine("      \"binaryDir\": \"${sourceDir}/build\",");
    if (!string.IsNullOrWhiteSpace(generator))
      sb.AppendLine($"      \"generator\": {JsonOutput.Quote(generator)},");
    sb.AppendLine("      \"cacheVariables\": {");

    var entries = cacheVariables.ToList();
    for (var i = 0; i < entries.Count; i++)
    {
      var comma = i == entries.Count - 1 ? string.Empty : ",";
      sb.AppendLine($"        {JsonOutput.Quote(entries[i].Key)}: {JsonOutput.Quote(entries[i].Value)}{comma}");
    }

    sb.AppendLine("      }");
    sb.AppendLine("    }");
    sb.AppendLine("  ],");
    sb.AppendLine("  \"buildPresets\": [");
    sb.AppendLine("    {");
    sb.AppendLine($"      \"name\": \"{PresetName}\",");
    sb.AppendLine($"      \"configurePreset\": \"{PresetName}\"");
    sb.AppendLine("    }");
    sb.AppendLine("  ]");
    sb.AppendLine("}");

    File.WriteAllText(path, sb.ToString());
  }
}
