using System.Runtime.InteropServices;
using forge.Models;

namespace forge;

/// <summary>
/// Hot reload support: the pinned engine dependency, the generated glue the
/// application calls, and the checks the mode needs to be usable.
/// </summary>
/// <remarks>
/// The engine is jet-live: it recompiles changed translation units, links them
/// into a patch library and redirects the running process's functions to the
/// new code, keeping statics and globals alive. That only works on debug
/// builds (unoptimised, unstripped), so hot mode forces one.
/// </remarks>
public static class HotReload
{
  /// <summary>The dependency key Forge injects when hot mode is on.</summary>
  public const string DependencyName = "jetlive";

  /// <summary>Where the generated glue lives, relative to the project.</summary>
  public const string GlueDirectory = ".config/forge/hot";

  // The engine, pinned to a commit tested against this Forge. It is a normal
  // git dependency, so `forge install` records it in forge.lock and the shared
  // cache serves it like any other.
  private const string GitUrl = "https://github.com/ddovod/jet-live.git";
  private const string PinnedRef = "394948ee312d83c75ca415ff9042d664678f7b38";

  /// <summary>
  /// Adds the engine to the in-memory configuration (the user's forge.lua is
  /// never touched). The dependency's options are set before the fetched
  /// project is configured, so its example and tests stay off.
  /// </summary>
  public static void EnsureDependency(ProjectConfig config)
  {
    if (config.Dependencies.ContainsKey(DependencyName))
      return;

    config.Dependencies[DependencyName] = new Dependency
    {
      Git = GitUrl,
      Tag = PinnedRef,
      Target = "jet-live",
      Options =
      {
        ["JET_LIVE_BUILD_EXAMPLE"] = "OFF",
        ["JET_LIVE_BUILD_TESTS"] = "OFF",
      },
    };
  }

  /// <summary>
  /// Writes the glue sources the application links: the init/update pair and
  /// the optional pre/post-reload hooks.
  /// </summary>
  public static void WriteGlue()
  {
    Directory.CreateDirectory(GlueDirectory);
    WriteIfChanged(Path.Combine(GlueDirectory, "forge_hot.h"), Header);
    WriteIfChanged(Path.Combine(GlueDirectory, "forge_hot.cpp"), Source);
  }

  /// <summary>
  /// The reason hot mode cannot work with this configuration, or null when it
  /// can. The limits are the engine's: it patches unoptimised code, in a single
  /// thread, without moving the address space around.
  /// </summary>
  public static string? Validate(ProjectConfig config, bool release)
  {
    if (release)
      return "hot reload needs a debug build — drop `--release` (the engine patches unoptimised, unstripped code).";

    if (config.Build.Unity)
      return "hot reload cannot be combined with `unity = true`: a save would recompile the whole unity blob.";

    if (config.Build.Modules)
      return "hot reload cannot be combined with `modules = true`.";

    var preset = config.Build.Presets.FirstOrDefault(name => name is "asan" or "tsan" or "ubsan" or "msan");
    if (preset is not null)
      return $"hot reload cannot be combined with the `{preset}` preset (sanitizers move the address space the patch library is loaded into).";

    if (config.Build.Presets.Contains("lto"))
      return "hot reload cannot be combined with the `lto` preset (the patch library is linked separately).";

    return null;
  }

  /// <summary>
  /// True when the build tree uses Ninja, whose depfiles jet-live reads to
  /// track header dependencies — and which it deletes unless the build asks it
  /// to keep them.
  /// </summary>
  public static bool IsNinjaGenerator()
  {
    var cache = Path.Combine("build", "CMakeCache.txt");
    if (!File.Exists(cache))
      return false;

    foreach (var line in File.ReadLines(cache))
    {
      if (line.StartsWith("CMAKE_GENERATOR:", StringComparison.Ordinal) &&
          line.Contains("Ninja", StringComparison.OrdinalIgnoreCase))
        return true;
    }

    return false;
  }

  /// <summary>Sends the engine's reload signal (SIGUSR1) to a running process.</summary>
  public static bool SendReloadSignal(int pid)
  {
    if (OperatingSystem.IsWindows())
      return false;

    // SIGUSR1 is 10 on Linux and 30 on macOS.
    var signal = OperatingSystem.IsMacOS() ? 30 : 10;
    return kill(pid, signal) == 0;
  }

  private static void WriteIfChanged(string path, string content)
  {
    if (File.Exists(path) && File.ReadAllText(path) == content)
      return;
    File.WriteAllText(path, content);
  }

  [DllImport("libc", SetLastError = true)]
  private static extern int kill(int pid, int sig);

  private const string Header = """
#pragma once

// Generated by Forge (`forge hot`). Do not edit.
//
// Call forge_hot_init() once at startup and forge_hot_update() from the main
// loop. The loop must be single-threaded: the engine patches the running
// process and does not support reloading while other threads run.
//
// A type whose layout changed is the one thing the engine cannot fix: an
// object already allocated with the old layout will be read with the new one,
// silently producing wrong values. Recreate such objects in these hooks —
// define them in your own sources and the glue will call them:
//
//   extern "C" void forge_hot_pre_reload()  { delete g_state; g_state = nullptr; }
//   extern "C" void forge_hot_post_reload() { g_state = new State{}; }

void forge_hot_init();
void forge_hot_update();

extern "C" void forge_hot_pre_reload() __attribute__((weak));
extern "C" void forge_hot_post_reload() __attribute__((weak));
""";

  private const string Source = """
#include "forge_hot.h"

#include <jet/live/Live.hpp>

#include <chrono>
#include <cstdio>
#include <memory>
#include <string>
#include <thread>

namespace
{
  class ForgeHotListener : public jet::ILiveListener
  {
  public:
    void onLog(jet::LogSeverity severity, const std::string& text) override
    {
      const char* level = severity == jet::LogSeverity::kError     ? "error"
                          : severity == jet::LogSeverity::kWarning ? "warn"
                                                                   : "info";
      std::printf("[hot %s] %s\n", level, text.c_str());
      std::fflush(stdout);
    }

    void onCodePreLoad() override
    {
      if (forge_hot_pre_reload != nullptr)
        forge_hot_pre_reload();
    }

    void onCodePostLoad() override
    {
      if (forge_hot_post_reload != nullptr)
        forge_hot_post_reload();
    }
  };

  std::unique_ptr<jet::Live> g_live;
}

void forge_hot_init()
{
  jet::LiveConfig config;
  config.workerThreadsCount = 2;
  g_live = std::make_unique<jet::Live>(std::make_unique<ForgeHotListener>(), config);

  // Initialization runs in a background thread; wait for it so the first save
  // has something to reload.
  for (int i = 0; i < 100 && !g_live->isInitialized(); ++i)
  {
    g_live->update();
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
  }
}

void forge_hot_update()
{
  if (g_live)
    g_live->update();
}
""";
}
