site_name: Forge CLI (C++ Meta-Build System)
theme:
  name: readthedocs
  highlightjs: true
  navigation_depth: 3
  titles_only: false
  collapse_navigation: false
  sticky_navigation: true
nav:
  - Home: index.md
  - Prerequisites: prerequisites.md
  - Project Configuration: project-configuration.md
  - Build System: build-system.md
  - Project Scaffolding: project-scaffolding.md
  - Dependency Management: dependency-management.md
  - Workspaces: workspaces.md
  - Custom Setup Scripts: custom-setup.md
  - CLI Reference: cli-reference.md
  - Lua Reference: lua-reference.md
plugins:
  - search
markdown_extensions:
  - admonition
