using System.Text;
using DotMake.CommandLine;
using forge.Models;
using Spectre.Console;

namespace forge.Commands;

/// <summary>
/// Generates a CI workflow for the project, tailored to what the configuration
/// actually needs: the dependency channels in use, whether tests exist, whether
/// the project is versioned, and which quality tools it has opted into.
/// </summary>
/// <remarks>
/// The generated file is deterministic, so <c>--check</c> can be used in CI to
/// catch a workflow that has drifted from the configuration. An existing file
/// is never overwritten without <c>--force</c>.
/// </remarks>
/// <example>
/// <code>
/// forge ci                          # .github/workflows/forge.yml
/// forge ci --provider gitlab        # .gitlab-ci.yml
/// forge ci --runners ubuntu-latest  # a single runner
/// forge ci --check                  # fail when out of date (for CI)
/// </code>
/// </example>
[CliCommand(Name = "ci", Description = "Generate a CI workflow for the project.", Parent = typeof(RootCommand))]
public class CiCommand
{
  [CliOption(Description = "Provider: github (default) or gitlab", Required = false)]
  public string Provider { get; set; } = "github";

  [CliOption(Description = "Runners to target, comma-separated", Required = false)]
  public string Runners { get; set; } = "ubuntu-latest,macos-latest";

  [CliOption(Description = "Configurations to build, comma-separated (release, debug)", Required = false)]
  public string Configurations { get; set; } = "release,debug";

  [CliOption(Description = "Overwrite an existing workflow", Required = false)]
  public bool Force { get; set; }

  [CliOption(Description = "Fail when the workflow is out of date instead of writing it", Required = false)]
  public bool Check { get; set; }

  public async Task<int> RunAsync()
  {
    var config = await ProjectConfigManager.LoadConfigAsync();
    if (config == null)
    {
      AnsiConsole.MarkupLine("[bold red]Error:[/] Not a forge project. `forge.lua` not found or is missing project name.");
      return 1;
    }

    var provider = Provider.Trim().ToLowerInvariant();
    var path = provider switch
    {
      "github" => Path.Combine(".github", "workflows", "forge.yml"),
      "gitlab" => ".gitlab-ci.yml",
      _ => null
    };

    if (path == null)
    {
      AnsiConsole.MarkupLine($"[bold red]Error:[/] unknown provider `{Provider}`. Use `github` or `gitlab`.");
      return 1;
    }

    var runners = Split(Runners);
    var configurations = Split(Configurations);
    if (runners.Count == 0 || configurations.Count == 0)
    {
      AnsiConsole.MarkupLine("[bold red]Error:[/] --runners and --configurations cannot be empty.");
      return 1;
    }

    var content = provider == "github"
      ? GitHubWorkflow(config, runners, configurations)
      : GitLabPipeline(config, runners, configurations);

    if (Check)
    {
      if (!File.Exists(path))
      {
        AnsiConsole.MarkupLine($"[bold red]{path} is missing[/] — run `forge ci`.");
        return 1;
      }

      if (File.ReadAllText(path) != content)
      {
        AnsiConsole.MarkupLine($"[bold red]{path} is out of date[/] — run `forge ci --force`.");
        return 1;
      }

      AnsiConsole.MarkupLine($"[green]{path} is up to date.[/]");
      return 0;
    }

    if (File.Exists(path) && !Force)
    {
      if (File.ReadAllText(path) == content)
      {
        AnsiConsole.MarkupLine($"[green]{path} is already up to date.[/]");
        return 0;
      }

      AnsiConsole.MarkupLine(
        $"[bold red]Error:[/] `{path}` already exists and differs — pass `--force` to overwrite it.");
      return 1;
    }

    var directory = Path.GetDirectoryName(path);
    if (!string.IsNullOrEmpty(directory))
      Directory.CreateDirectory(directory);

    File.WriteAllText(path, content);
    AnsiConsole.MarkupLine($"[green]Wrote {path}[/] ({runners.Count * configurations.Count} job(s)).");
    return 0;
  }

  private static List<string> Split(string value) =>
    value.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries).ToList();

  private static bool HasConan(ProjectConfig config) => config.ConanDependencies.Count != 0;

  private static bool HasVcpkg(ProjectConfig config) => config.VcpkgDependencies.Count != 0;

  private static bool HasPkgConfig(ProjectConfig config) => config.PkgConfigDependencies.Count != 0;

  private static bool IsVersioned(ProjectConfig config) => !string.IsNullOrWhiteSpace(config.Project.Version);

  /// <summary>A GitHub Actions workflow using the matrix the flags describe.</summary>
  private static string GitHubWorkflow(ProjectConfig config, List<string> runners, List<string> configurations)
  {
    var sb = new StringBuilder();
    sb.AppendLine("# Generated by `forge ci`. Edit freely, then re-run with `--force` to regenerate.");
    sb.AppendLine("name: Build");
    sb.AppendLine();
    sb.AppendLine("on:");
    sb.AppendLine("  push:");
    sb.AppendLine("    branches: [main]");
    sb.AppendLine("  pull_request:");
    sb.AppendLine("  workflow_dispatch:");
    sb.AppendLine();
    sb.AppendLine("jobs:");
    sb.AppendLine("  build:");
    sb.AppendLine("    name: ${{ matrix.runner }} / ${{ matrix.config }}");
    sb.AppendLine("    runs-on: ${{ matrix.runner }}");
    sb.AppendLine("    strategy:");
    sb.AppendLine("      fail-fast: false");
    sb.AppendLine("      matrix:");
    sb.AppendLine($"        runner: [{string.Join(", ", runners)}]");
    sb.AppendLine($"        config: [{string.Join(", ", configurations)}]");
    sb.AppendLine("    steps:");
    sb.AppendLine("      - uses: actions/checkout@v4");
    sb.AppendLine();
    sb.AppendLine("      - name: Install Forge");
    sb.AppendLine("        run: curl -sSL https://raw.githubusercontent.com/0xThurling/forge-cli/refs/heads/main/install.sh | bash");
    sb.AppendLine();
    // The install steps come from the same tool table `forge setup` and
    // `forge doctor` use, so a project's CI cannot drift from them.
    var linuxPackages = string.Join(" ", new[] { "cmake", "ninja", "c++", "clang-format", "clang-tidy" }
      .Select(name => ToolRequirements.Find(name)?.PackageFor("apt-get") ?? name)
      .Distinct());
    var brewPackages = string.Join(" ", new[] { "cmake", "ninja" }
      .Select(name => ToolRequirements.Find(name)?.PackageFor("brew") ?? name)
      .Distinct());

    sb.AppendLine("      - name: Toolchain");
    sb.AppendLine("        if: runner.os == 'Linux'");
    sb.AppendLine("        run: |");
    sb.AppendLine("          sudo apt-get update");
    sb.AppendLine($"          sudo apt-get install -y {linuxPackages}");
    sb.AppendLine();
    sb.AppendLine("      - name: Toolchain (macOS)");
    sb.AppendLine("        if: runner.os == 'macOS'");
    sb.AppendLine($"        run: brew install {brewPackages}");

    if (HasConan(config))
    {
      sb.AppendLine();
      sb.AppendLine("      - name: Conan");
      sb.AppendLine("        run: pipx install conan");
    }

    if (HasVcpkg(config))
    {
      sb.AppendLine();
      sb.AppendLine("      - name: vcpkg");
      sb.AppendLine("        run: echo \"VCPKG_ROOT=$VCPKG_INSTALLATION_ROOT\" >> \"$GITHUB_ENV\"");
    }

    if (HasPkgConfig(config))
    {
      sb.AppendLine();
      sb.AppendLine("      # TODO: install the development packages for these pkg-config modules:");
      sb.AppendLine($"      #   {string.Join(", ", config.PkgConfigDependencies)}");
    }

    sb.AppendLine();
    sb.AppendLine("      - name: Build");
    sb.AppendLine("        run: forge build --${{ matrix.config }}");

    if (config.Testing)
    {
      sb.AppendLine();
      sb.AppendLine("      - name: Test");
      sb.AppendLine("        run: forge test --${{ matrix.config }}");
    }

    if (File.Exists(".clang-tidy"))
    {
      sb.AppendLine();
      sb.AppendLine("      - name: Lint");
      sb.AppendLine("        if: runner.os == 'Linux'");
      sb.AppendLine("        run: forge lint");
    }

    if (File.Exists(".clang-format"))
    {
      sb.AppendLine();
      sb.AppendLine("      - name: Format check");
      sb.AppendLine("        if: runner.os == 'Linux'");
      sb.AppendLine("        run: forge format --check");
    }

    if (IsVersioned(config))
    {
      sb.AppendLine();
      sb.AppendLine("      - name: Package");
      sb.AppendLine("        if: matrix.config == 'release'");
      sb.AppendLine("        run: forge publish --format TGZ --output dist");
      sb.AppendLine();
      sb.AppendLine("      - uses: actions/upload-artifact@v4");
      sb.AppendLine("        if: matrix.config == 'release'");
      sb.AppendLine("        with:");
      sb.AppendLine("          name: package-${{ matrix.runner }}");
      sb.AppendLine("          path: dist/*");
    }

    return sb.ToString();
  }

  /// <summary>A GitLab pipeline: one job per runner, release configuration.</summary>
  private static string GitLabPipeline(ProjectConfig config, List<string> runners, List<string> configurations)
  {
    var sb = new StringBuilder();
    sb.AppendLine("# Generated by `forge ci --provider gitlab`.");
    sb.AppendLine("# Edit freely, then re-run with `--force` to regenerate.");
    sb.AppendLine("stages: [build]");
    sb.AppendLine();
    sb.AppendLine("default:");
    sb.AppendLine("  image: ubuntu:24.04");
    sb.AppendLine("  before_script:");
    sb.AppendLine("    - apt-get update");
    sb.AppendLine("    - apt-get install -y curl git cmake ninja-build g++");
    sb.AppendLine("    - curl -sSL https://raw.githubusercontent.com/0xThurling/forge-cli/refs/heads/main/install.sh | bash");
    sb.AppendLine("    - export PATH=\"$HOME/.local/bin:$PATH\"");

    if (HasConan(config))
    {
      sb.AppendLine("    - pipx install conan");
    }

    if (HasVcpkg(config))
    {
      sb.AppendLine("    - export VCPKG_ROOT=\"${VCPKG_ROOT:-$CI_PROJECT_DIR/vcpkg}\"");
    }

    sb.AppendLine();
    sb.AppendLine("# Runners: " + string.Join(", ", runners));

    foreach (var configuration in configurations)
    {
      sb.AppendLine();
      sb.AppendLine($"build:{configuration}:");
      sb.AppendLine("  stage: build");
      sb.AppendLine("  script:");
      sb.AppendLine($"    - forge build --{configuration}");

      if (config.Testing)
        sb.AppendLine($"    - forge test --{configuration}");

      if (IsVersioned(config) && configuration == "release")
      {
        sb.AppendLine("    - forge publish --format TGZ --output dist");
        sb.AppendLine("  artifacts:");
        sb.AppendLine("    paths: [dist/]");
      }
    }

    return sb.ToString();
  }
}
