using System.Text;
using forge.CMakeGeneration.Sections;
using forge.Models;

namespace forge.CMakeGeneration;

public class CMakeRegistry
{
  private static CMakeRegistry? _instance;

  public static CMakeRegistry Instance => _instance ??= new CMakeRegistry();

  private readonly Dictionary<string, ICMakeSection> _sections = [];

  private bool _initialized = false;
  private string _standard = "20";

  private CMakeRegistry() {}

  public void Register(ICMakeSection section) {
    _sections[section.Name] = section;
  }

  public void Initialize() {
    if (_initialized) return;

    Register(new StandardSection(_standard));
    Register(new FeaturesSection());
    Register(new FetchContentSection());
    Register(new ConanSection());
    Register(new ProjectTargetSection());
    Register(new LinkingSection());
    Register(new CustomCMakeSection());
    Register(new TestingSection());

    _initialized = true;
  }

  public string Generate(ProjectConfig config, string standard) {
    _standard = standard;

    Initialize();

    var sb = new StringBuilder();
    sb.AppendLine("# This file is generated by Forge. DO NOT TOUCH");
    sb.AppendLine();

    foreach (var section in _sections.Values.Where(s => s.IsEnabled(config)).OrderBy(s => s.Priority))
    {
      var content = section.Generate(config);
      if (!string.IsNullOrWhiteSpace(content))
      {
         sb.AppendLine(content);
         sb.AppendLine();
      }
    }

    return sb.ToString();
  }
}
