using System.Text;
using forge.CMakeGeneration.Sections;
using forge.Models;
using Spectre.Console;

namespace forge.CMakeGeneration;

public class CMakeRegistry
{
  private static CMakeRegistry? _instance;

  public static CMakeRegistry Instance => _instance ??= new CMakeRegistry();

  private readonly Dictionary<string, ICMakeSection> _sections = [];

  private bool _initialized = false;

  private CMakeRegistry() { }

  public void Register(ICMakeSection section)
  {
    _sections[section.Name] = section;
  }

  public void Initialize()
  {
    if (_initialized) return;

    Register(new StandardSection());
    Register(new FeaturesSection());
    Register(new FetchContentSection());
    Register(new ConanSection());
    Register(new VcpkgSection());
    Register(new PkgConfigSection());
    Register(new FlagsSection());
    Register(new LuaOptionsSection());
    Register(new ProjectTargetSection());
    Register(new LinkingSection());
    Register(new CustomCMakeSection());
    Register(new TestingSection());
    Register(new PackagingSection());

    _initialized = true;
  }

  /// <summary>Priority used when a Lua section asks to go last.</summary>
  private const int LastPriority = 1000;

  /// <summary>The sections a Lua script can anchor to, in emission order.</summary>
  public IEnumerable<string> SectionNames => _sections.Keys.OrderBy(key => _sections[key].Priority);

  /// <summary>
  /// Registers the sections Lua build scripts asked for, resolving each
  /// requested anchor against the built-in sections.
  /// </summary>
  public void ApplyLuaSections(BuildContext context)
  {
    Initialize();

    // Sections from a previous build must not survive: a script that stops
    // registering one (an edit while `forge watch` runs) would otherwise keep
    // it in the generated file for the rest of the process.
    foreach (var name in _sections.Keys
               .Where(key => key.StartsWith("lua:", StringComparison.Ordinal))
               .ToList())
    {
      _sections.Remove(name);
    }

    foreach (var section in context.LuaSections)
      Register(new LuaSection(section, ResolvePriority(section)));
  }

  /// <summary>
  /// Turns a requested position into a priority: a number, "first", "last", or
  /// "before:&lt;section&gt;" / "after:&lt;section&gt;".
  /// </summary>
  private int ResolvePriority(LuaCmakeSection section)
  {
    var position = section.Position.Trim();
    if (position.Length == 0)
      return LastPriority;

    if (int.TryParse(position, out var number))
      return number;

    if (string.Equals(position, "first", StringComparison.OrdinalIgnoreCase))
      return 0;
    if (string.Equals(position, "last", StringComparison.OrdinalIgnoreCase))
      return LastPriority;

    var separator = position.IndexOf(':');
    if (separator > 0)
    {
      var mode = position[..separator].Trim().ToLowerInvariant();
      var anchor = position[(separator + 1)..].Trim();

      if (mode is "before" or "after")
      {
        if (_sections.TryGetValue(anchor, out var target))
          return mode == "before" ? target.Priority - 1 : target.Priority + 1;

        AnsiConsole.MarkupLine(
          $"[yellow]Warning:[/] section `{section.Name}` anchors to unknown section `{anchor}`; " +
          $"known: {string.Join(", ", SectionNames)}. Placing it last.");
        return LastPriority;
      }
    }

    AnsiConsole.MarkupLine(
      $"[yellow]Warning:[/] section `{section.Name}` has an unreadable position `{section.Position}`; " +
      "use a number, \"first\", \"last\", \"before:<section>\" or \"after:<section>\". Placing it last.");
    return LastPriority;
  }

  public string Generate(BuildContext context)
  {
    Initialize();
    ApplyLuaSections(context);

    var sb = new StringBuilder();
    sb.AppendLine("# This file is generated by Forge. DO NOT TOUCH");
    sb.AppendLine();

    foreach (var section in _sections.Values.Where(s => s.IsEnabled(context)).OrderBy(s => s.Priority))
    {
      var content = section.Generate(context);
      if (!string.IsNullOrWhiteSpace(content))
      {
        sb.AppendLine(content);
        sb.AppendLine();
      }
    }

    return sb.ToString();
  }
}
